#include "overrides.h"

static const struct core_override_option gambatte_core_option_overrides[] = {
	{
		.key = "gambatte_gb_colorization",
		.info = "'Auto' selects the 'best' palette. 'Internal' uses 'Internal Palette' option. 'Custom' loads user palette from system directory.",
	},
	{
		.key = "gambatte_gb_internal_palette",
		.info = "Selects palette used when 'GB Colorization' is set to 'Internal.'",
		.options = {
			[50] = { "Special 4 (TI-83 Legacy)", "Special 4" },
			[51] = { "TWB64 - Pack 1",           "TWB64 1" },
			[52] = { "TWB64 - Pack 2",           "TWB64 2" },
			[53] = { "PixelShift - Pack 1",      "PixelShift" },
		}
	},
	{
		.key = "gambatte_gb_palette_twb64_1",
		.desc = "TWB64 - Pack 1",
		.info = "Selects palette used when 'Internal Palette' is set to 'TWB64 1'",
		.default_value = "Aqours Blue",
		.options = {
			{ "TWB64 001 - Aqours Blue",               "Aqours Blue" },
			{ "TWB64 002 - Anime Expo Ver.",           "Anime Expo Ver." },
			{ "TWB64 003 - SpongeBob Yellow",          "SpongeBob Yellow" },
			{ "TWB64 004 - Patrick Star Pink",         "Patrick Star Pink" },
			{ "TWB64 005 - Neon Red",                  "Neon Red" },
			{ "TWB64 006 - Neon Blue",                 "Neon Blue" },
			{ "TWB64 007 - Neon Yellow",               "Neon Yellow" },
			{ "TWB64 008 - Neon Green",                "Neon Green" },
			{ "TWB64 009 - Neon Pink",                 "Neon Pink" },
			{ "TWB64 010 - Mario Red",                 "Mario Red" },
			{ "TWB64 011 - Nick Orange",               "Nick Orange" },
			{ "TWB64 012 - Virtual Boy Ver.",          "Virtual Boy Ver." },
			{ "TWB64 013 - Golden Wild",               "Golden Wild" },
			{ "TWB64 014 - Builder Yellow",            "Builder Yellow" },
			{ "TWB64 015 - Classic Blurple",           "Classic Blurple" },
			{ "TWB64 016 - 765 Production Ver.",       "765 Production Ver." },
			{ "TWB64 017 - Superball Ivory",           "Superball Ivory" },
			{ "TWB64 018 - Crunchyroll Orange",        "Crunchyroll Orange" },
			{ "TWB64 019 - Muse Pink",                 "Muse Pink" },
			{ "TWB64 020 - Nijigasaki Yellow",         "Nijigasaki Yellow" },
			{ "TWB64 021 - Gamate Ver.",               "Gamate Ver." },
			{ "TWB64 022 - Greenscale Ver.",           "Greenscale Ver." },
			{ "TWB64 023 - Odyssey Gold",              "Odyssey Gold" },
			{ "TWB64 024 - Super Saiyan God",          "Super Saiyan God" },
			{ "TWB64 025 - Super Saiyan Blue",         "Super Saiyan Blue" },
			{ "TWB64 026 - Bizarre Pink",              "Bizarre Pink" },
			{ "TWB64 027 - Nintendo Switch Lite Ver.", "Switch Lite Ver." },
			{ "TWB64 028 - Game.com Ver.",             "Game.com Ver." },
			{ "TWB64 029 - Sanrio Pink",               "Sanrio Pink" },
			{ "TWB64 030 - BANDAI NAMCO Ver.",         "BANDAI NAMCO Ver." },
			{ "TWB64 031 - Cosmo Green",               "Cosmo Green" },
			{ "TWB64 032 - Wanda Pink",                "Wanda Pink" },
			{ "TWB64 033 - Link's Awakening DX Ver.",  "Zelda DX Ver." },
			{ "TWB64 034 - Travel Wood",               "Travel Wood" },
			{ "TWB64 035 - Pokemon Ver.",              "Pokemon Ver." },
			{ "TWB64 036 - Game Grump Orange",         "Game Grump Orange" },
			{ "TWB64 037 - Scooby-Doo Mystery Ver.",   "Scooby-Doo Ver." },
			{ "TWB64 038 - Pokemon mini Ver.",         "Pokemon mini Ver." },
			{ "TWB64 039 - Supervision Ver.",          "Supervision Ver." },
			{ "TWB64 040 - DMG Ver.",                  "DMG Ver." },
			{ "TWB64 041 - Pocket Ver.",               "Pocket Ver." },
			{ "TWB64 042 - Light Ver.",                "Light Ver." },
			{ "TWB64 043 - Miraitowa Blue",            "Miraitowa Blue" },
			{ "TWB64 044 - Someity Pink",              "Someity Pink" },
			{ "TWB64 045 - Pikachu Yellow",            "Pikachu Yellow" },
			{ "TWB64 046 - Eevee Brown",               "Eevee Brown" },
			{ "TWB64 047 - Microvision Ver.",          "Microvision Ver." },
			{ "TWB64 048 - TI-83 Ver.",                "TI-83 Ver." },
			{ "TWB64 049 - Aegis Cherry",              "Aegis Cherry" },
			{ "TWB64 050 - Labo Fawn",                 "Labo Fawn" },
			{ "TWB64 051 - MILLION LIVE GOLD!",        "MILLION LIVE GOLD!" },
			{ "TWB64 052 - Tokyo Midtown Ver.",        "Tokyo Midtown Ver." },
			{ "TWB64 053 - VMU Ver.",                  "VMU Ver." },
			{ "TWB64 054 - Game Master Ver.",          "Game Master Ver." },
			{ "TWB64 055 - Android Green",             "Android Green" },
			{ "TWB64 056 - Ticketmaster Azure",        "Ticketmaster Azure" },
			{ "TWB64 057 - Google Red",                "Google Red" },
			{ "TWB64 058 - Google Blue",               "Google Blue" },
			{ "TWB64 059 - Google Yellow",             "Google Yellow" },
			{ "TWB64 060 - Google Green",              "Google Green" },
			{ "TWB64 061 - WonderSwan Ver.",           "WonderSwan Ver." },
			{ "TWB64 062 - Neo Geo Pocket Ver.",       "Neo Geo Pocket Ver." },
			{ "TWB64 063 - Dew Green",                 "Dew Green" },
			{ "TWB64 064 - Coca-Cola Red",             "Coca-Cola Red" },
			{ "TWB64 065 - GameKing Ver.",             "GameKing Ver." },
			{ "TWB64 066 - Do The Dew Ver.",           "Do The Dew Ver." },
			{ "TWB64 067 - Digivice Ver.",             "Digivice Ver." },
			{ "TWB64 068 - Bikini Bottom Ver.",        "Bikini Bottom Ver." },
			{ "TWB64 069 - Blossom Pink",              "Blossom Pink" },
			{ "TWB64 070 - Bubbles Blue",              "Bubbles Blue" },
			{ "TWB64 071 - Buttercup Green",           "Buttercup Green" },
			{ "TWB64 072 - NASCAR Ver.",               "NASCAR Ver." },
			{ "TWB64 073 - Lemon-Lime Green",          "Lemon-Lime Green" },
			{ "TWB64 074 - Mega Man V Ver.",           "Mega Man V Ver." },
			{ "TWB64 075 - Tamagotchi Ver.",           "Tamagotchi Ver." },
			{ "TWB64 076 - Phantom Red",               "Phantom Red" },
			{ "TWB64 077 - Halloween Ver.",            "Halloween Ver." },
			{ "TWB64 078 - Christmas Ver.",            "Christmas Ver." },
			{ "TWB64 079 - Cardcaptor Pink",           "Cardcaptor Pink" },
			{ "TWB64 080 - Pretty Guardian Gold",      "Pretty Guardian Gold" },
			{ "TWB64 081 - Camouflage Ver.",           "Camoflauge Ver." },
			{ "TWB64 082 - Legendary Super Saiyan",    "Legendary Sp. Saiyan" },
			{ "TWB64 083 - Super Saiyan Rose",         "Super Saiyan Rose" },
			{ "TWB64 084 - Super Saiyan",              "Super Saiyan" },
			{ "TWB64 085 - Perfected Ultra Instinct",  "Mst. Ult. Instinct" },
			{ "TWB64 086 - Saint Snow Red",            "Saint Snow Red" },
			{ "TWB64 087 - Yellow Banana",             "Yellow Banana" },
			{ "TWB64 088 - Green Banana",              "Green Banana" },
			{ "TWB64 089 - Super Saiyan 3",            "Super Saiyan 3" },
			{ "TWB64 090 - Super Saiyan Blue Evolved", "Sp. Saiyan Blue Evo." },
			{ "TWB64 091 - Pocket Tales Ver.",         "Pocket Tales Ver." },
			{ "TWB64 092 - Investigation Yellow",      "Investigation Yellow" },
			{ "TWB64 093 - S.E.E.S. Blue",             "S.E.E.S. Blue" },
			{ "TWB64 094 - Game Awards Cyan",          "Game Awards Cyan" },
			{ "TWB64 095 - Hokage Orange",             "Hokage Orange" },
			{ "TWB64 096 - Straw Hat Red",             "Straw Hat Red" },
			{ "TWB64 097 - Sword Art Cyan",            "Sword Art Cyan" },
			{ "TWB64 098 - Deku Alpha Emerald",        "Deku Alpha Emerald" },
			{ "TWB64 099 - Blue Stripes Ver.",         "Blue Stripes Ver." },
			{ "TWB64 100 - Stone Orange",              "Stone Orange" },
			{ NULL, NULL }
		}
	},
	{
		.key = "gambatte_gb_palette_twb64_2",
		.desc = "TWB64 - Pack 2",
		.info = "Selects palette used when 'Internal Palette' is set to 'TWB64 2'",
		.options = {
			{ "TWB64 101 - 765PRO Pink",               "765PRO Pink" },
			{ "TWB64 102 - CINDERELLA Blue",           "CINDERELLA Blue" },
			{ "TWB64 103 - MILLION Yellow!",           "MILLION Yellow!" },
			{ "TWB64 104 - SideM Green",               "SideM Green" },
			{ "TWB64 105 - SHINY Sky Blue",            "SHINY Sky Blue" },
			{ "TWB64 106 - Angry Volcano Ver.",        "Angry Volcano Ver." },
			{ "TWB64 107 - Yo-kai Pink",               "Yo-kai Pink" },
			{ "TWB64 108 - Yo-kai Green",              "Yo-kai Green" },
			{ "TWB64 109 - Yo-kai Blue",               "Yo-kai Blue" },
			{ "TWB64 110 - Yo-kai Purple",             "Yo-kai Purple" },
			{ "TWB64 111 - Aquatic Iro",               "Aquatic Iro" },
			{ "TWB64 112 - Tea Midori",                "Tea Midori" },
			{ "TWB64 113 - Sakura Pink",               "Sakura Pink" },
			{ "TWB64 114 - Wisteria Murasaki",         "Wisteria Murasaki" },
			{ "TWB64 115 - Oni Aka",                   "Oni Aka" },
			{ "TWB64 116 - Golden Kiiro",              "Golden Kiiro" },
			{ "TWB64 117 - Silver Shiro",              "Silver Shiro" },
			{ "TWB64 118 - Fruity Orange",             "Fruity Orange" },
			{ "TWB64 119 - AKB48 Pink",                "AKB48 Pink" },
			{ "TWB64 120 - Miku Blue",                 "Miku Blue" },
			{ "TWB64 121 - Fairy Tail Red",            "Fairy Tail Red" },
			{ "TWB64 122 - Survey Corps Brown",        "Survey Corps Brown" },
			{ "TWB64 123 - Island Green",              "Island Green" },
			{ "TWB64 124 - Mania Plus Green",          "Mania Plus Green" },
			{ "TWB64 125 - Ninja Turtle Green",        "Ninja Turtle Green" },
			{ "TWB64 126 - Slime Blue",                "Slime Blue" },
			{ "TWB64 127 - Lime Midori",               "Lime Midori" },
			{ "TWB64 128 - Ghostly Aoi",               "Ghostly Aoi" },
			{ "TWB64 129 - Retro Bogeda",              "Retro Bogeda" },
			{ "TWB64 130 - Royal Blue",                "Royal Blue" },
			{ "TWB64 131 - Neon Purple",               "Neon Purple" },
			{ "TWB64 132 - Neon Orange",               "Neon Orange" },
			{ "TWB64 133 - Moonlight Vision",          "Moonlight Vision" },
			{ "TWB64 134 - Tokyo Red",                 "Tokyo Red" },
			{ "TWB64 135 - Paris Gold",                "Paris Gold" },
			{ "TWB64 136 - Beijing Blue",              "Beijing Blue" },
			{ "TWB64 137 - Pac-Man Yellow",            "Pac-Man Yellow" },
			{ "TWB64 138 - Irish Green",               "Irish Green" },
			{ "TWB64 139 - Kakarot Orange",            "Kakarot Orange" },
			{ "TWB64 140 - Dragon Ball Orange",        "Dragon Ball Orange" },
			{ "TWB64 141 - Christmas Gold",            "Christmas Gold" },
			{ "TWB64 142 - Pepsi-Cola Blue",           "Pepsi Blue" },
			{ "TWB64 143 - Bubblun Green",             "Bubblun Green" },
			{ "TWB64 144 - Bobblun Blue",              "Bobblun Blue" },
			{ "TWB64 145 - Baja Blast Storm",          "Baja Blast Storm" },
			{ "TWB64 146 - Olympic Gold",              "Olympic Gold" },
			{ "TWB64 147 - Value Orange",              "Value Orange" },
			{ "TWB64 148 - Liella Purple!",            "Liella Purple!" },
			{ "TWB64 149 - Olympic Silver",            "Olympic Silver" },
			{ "TWB64 150 - Olympic Bronze",            "Olympic Bronze" },
			{ "TWB64 151 - ANA Sky Blue",              "ANA Sky Blue" },
			{ "TWB64 152 - Nijigasaki Orange",         "Nijigasaki Orange" },
			{ "TWB64 153 - HoloBlue",                  "HoloBlue" },
			{ "TWB64 154 - Wrestling Red",             "Wrestling Red" },
			{ "TWB64 155 - Yoshi Egg Green",           "Yoshi Egg Green" },
			{ "TWB64 156 - Pokedex Red",               "Pokedex Red" },
			{ "TWB64 157 - Disney Dream Blue",         "Disney Dream Blue" },
			{ "TWB64 158 - Xbox Green",                "Xbox Green" },
			{ "TWB64 159 - Sonic Mega Blue",           "Sonic Mega Blue" },
			{ "TWB64 160 - G4 Orange",                 "G4 Orange" },
			{ "TWB64 161 - Scarlett Green",            "Scarlett Green" },
			{ "TWB64 162 - Glitchy Blue",              "Glitchy Blue" },
			{ "TWB64 163 - Classic LCD",               "Classic LCD" },
			{ "TWB64 164 - 3DS Virtual Console Ver.",  "3DS VC Ver." },
			{ "TWB64 165 - PocketStation Ver.",        "PocketStation Ver." },
			{ "TWB64 166 - Game and Gold",             "Game and Gold" },
			{ "TWB64 167 - Smurfy Blue",               "Smurfy Blue" },
			{ "TWB64 168 - Swampy Ogre Green",         "Swampy Ogre Green" },
			{ "TWB64 169 - Sailor Spinach Green",      "Sailor Spinach Green" },
			{ "TWB64 170 - Shenron Green",             "Shenron Green" },
			{ "TWB64 171 - Berserk Blood",             "Berserk Blood" },
			{ "TWB64 172 - Super Star Pink",           "Super Star Pink" },
			{ "TWB64 173 - Gamebuino Classic Ver.",    "Gamebuino Clas. Ver." },
			{ "TWB64 174 - Barbie Pink",               "Barbie Pink" },
			{ "TWB64 175 - Star Command Green",        "Star Command Green" },
			{ "TWB64 176 - Nokia 3310 Ver.",           "Nokia 3310 Ver." },
			{ "TWB64 177 - Clover Green",              "Clover Green" },
			{ "TWB64 178 - Crash Orange",              "Crash Orange" },
			{ "TWB64 179 - Famicom Disk Yellow",       "Famicom Disk Yellow" },
			{ "TWB64 180 - Team Rocket Red",           "Team Rocket Red" },
			{ "TWB64 181 - SEIKO Timer Yellow",        "SEIKO Timer Yellow" },
			{ "TWB64 182 - PINK109",                   "PINK109" },
			{ "TWB64 183 - Doraemon Blue",             "Doraemon Blue" },
			{ "TWB64 184 - Fury Blue",                 "Fury Blue" },
			{ "TWB64 185 - Rockstar Orange",           "Rockstar Orange" },
			{ "TWB64 186 - Puyo Puyo Green",           "Puyo Puyo Green" },
			{ "TWB64 187 - Susan G. Pink",             "Susan G. Pink" },
			{ "TWB64 188 - Pizza Hut Red",             "Pizza Hut Red" },
			{ "TWB64 189 - Plumbob Green",             "Plumbob Green" },
			{ "TWB64 190 - Grand Ivory",               "Grand Ivory" },
			{ "TWB64 191 - Demon's Gold",              "Demon's Gold" },
			{ "TWB64 192 - SEGA Tokyo Blue",           "SEGA Tokyo Blue" },
			{ "TWB64 193 - Champion Blue",             "Champion Blue" },
			{ "TWB64 194 - DK Barrel Brown",           "DK Barrel Brown" },
			{ "TWB64 195 - Evangelion Green",          "Evangelion Green" },
			{ "TWB64 196 - Equestrian Purple",         "Equestrian Purple" },
			{ "TWB64 197 - Autobot Red",               "Autobot Red" },
			{ "TWB64 198 - Niconico Sea Green",        "Niconico Sea Green" },
			{ "TWB64 199 - Duracell Copper",           "Duracell Copper" },
			{ "TWB64 200 - TOKYO SKYTREE CLOUDY BLUE", "TOKYO SKYTREE BLUE" },
			{ NULL, NULL },
		}
	},
	{
		.key = "gambatte_gb_palette_pixelshift_1",
		.desc = "PixelShift",
		.info = "Selects palette used when 'Internal Palette' is set to 'PixelShift.'",
		.options = {
			{ "PixelShift 01 - Arctic Green",               "Arctic Green" },
			{ "PixelShift 02 - Arduboy",                    "Arduboy" },
			{ "PixelShift 03 - BGB 0.3 Emulator",           "BGB 0.3 Emulator" },
			{ "PixelShift 04 - Camouflage",                 "Camouflage" },
			{ "PixelShift 05 - Chocolate Bar",              "Chocolate Bar" },
			{ "PixelShift 06 - CMYK",                       "CMYK" },
			{ "PixelShift 07 - Cotton Candy",               "Cotton Candy" },
			{ "PixelShift 08 - Easy Greens",                "Easy Greens" },
			{ "PixelShift 09 - Gamate",                     "Gamate" },
			{ "PixelShift 10 - Game Boy Light",             "Game Boy Light" },
			{ "PixelShift 11 - Game Boy Pocket",            "Game Boy Pocket" },
			{ "PixelShift 12 - Game Boy Pocket Alt",        "Game Boy Pocket Alt" },
			{ "PixelShift 13 - Game Pocket Computer",       "Game Pocket Computer" },
			{ "PixelShift 14 - Game & Watch Ball",          "Game & Watch Ball" },
			{ "PixelShift 15 - GB Backlight Blue",          "GB BL Blue" },
			{ "PixelShift 16 - GB Backlight Faded",         "GB BL Faded" },
			{ "PixelShift 17 - GB Backlight Orange",        "GB BL Orange" },
			{ "PixelShift 18 - GB Backlight White ",        "GB BL White " },
			{ "PixelShift 19 - GB Backlight Yellow Dark",   "GB BL Yellow Dark" },
			{ "PixelShift 20 - GB Bootleg",                 "GB Bootleg" },
			{ "PixelShift 21 - GB Hunter",                  "GB Hunter" },
			{ "PixelShift 22 - GB Kiosk",                   "GB Kiosk" },
			{ "PixelShift 23 - GB Kiosk 2",                 "GB Kiosk 2" },
			{ "PixelShift 24 - GB New",                     "GB New" },
			{ "PixelShift 25 - GB Nuked",                   "GB Nuked" },
			{ "PixelShift 26 - GB Old",                     "GB Old" },
			{ "PixelShift 27 - GBP Bivert",                 "GBP Bivert" },
			{ "PixelShift 28 - GB Washed Yellow Backlight", "GB Washed Yellow BL" },
			{ "PixelShift 29 - Ghost",                      "Ghost" },
			{ "PixelShift 30 - Glow In The Dark",           "Glow In The Dark" },
			{ "PixelShift 31 - Gold Bar",                   "Gold Bar" },
			{ "PixelShift 32 - Grapefruit",                 "Grapefruit" },
			{ "PixelShift 33 - Gray Green Mix",             "Gray Green Mix" },
			{ "PixelShift 34 - Missingno",                  "Missingno" },
			{ "PixelShift 35 - MS-Dos",                     "MS-Dos" },
			{ "PixelShift 36 - Newspaper",                  "Newspaper" },
			{ "PixelShift 37 - Pip-Boy",                    "Pip-Boy" },
			{ "PixelShift 38 - Pocket Girl",                "Pocket Girl" },
			{ "PixelShift 39 - Silhouette",                 "Silhouette" },
			{ "PixelShift 40 - Sunburst",                   "Sunburst" },
			{ "PixelShift 41 - Technicolor",                "Technicolor" },
			{ "PixelShift 42 - Tron",                       "Tron" },
			{ "PixelShift 44 - Virtual Boy",                "Virtual Boy" },
			{ "PixelShift 45 - Wish",                       "Wish" },
			{ NULL,                                         NULL },
		}
	},
	{
		.key = "gambatte_gbc_color_correction",
		.info = "Adjusts colors to match the display of real GBC hardware. 'GBC Only' only applies correction when playing GBC games or using a GBC palette."
	},
	{
		.key = "gambatte_gbc_color_correction_mode",
		.desc = "CC Mode",
		.info = "'Accurate' produces output almost indistinguishable from a real GBC LCD panel. 'Fast' merely darkens colors and reduces saturation."
	},
	{
		.key = "gambatte_gbc_frontlight_position",
		.desc = "CC Frontlight",
		.info = "Simulates the GBC LCD panel when illuminated from different angles. This setting only applies when 'Color Correction Mode' is set to 'Accurate'."
	},
	{
		.key = "gambatte_dark_filter_level",
		.desc = "Dark Level",
		.info = "Enable luminosity-based brightness reduction. May be used to avoid glare/eye strain when playing games with white backgrounds."
	},
	{
		.key = "gambatte_gb_hwmode",
		.desc = "Hardware (restart)",
		.info = "Which type of hardware to emulate. 'Auto' is recommended. 'GBA' unlocks extra features in certain 'GBA enhanced' Game Boy Color games."
	},
	{
		.key = "gambatte_gb_bootloader",
		.desc = "Boot Logo (restart)",
	},
	{
		.key = "gambatte_mix_frames",
		.desc = "Blending",
		.info = "Simulates LCD ghosting effects. 'Simple' performs a 50:50 mix. 'Ghosting' mimics LCD response times with multiple buffered frames.",
		.options = {
			[2] = { "lcd_ghosting",         "Ghosting (Accurate)" },
			[3] = { "lcd_ghosting_fast",    "Ghosting (Fast)"     },
			[4] = { "lcd_ghosting_fastest", "Ghosting (Fastest)"  },
		}
	},
	{
		.key = "gambatte_audio_resampler",
		.info = "Specify which algorithm to use when resampling generated audio. 'Sinc' has the highest quality. 'Cosine' improves performance.",
	},
	{
		.key = "gambatte_up_down_allowed",
		.desc = "Opp. Directions",
		.info = "Enabling this will allow pressing / quickly alternating / holding both left and right (or up and down) directions at the same time."
	},
	{
		.key = "gambatte_rumble_level",
		.blocked = true
	},
	{
		.key = "gambatte_show_gb_link_settings",
		.blocked = true
	},
	{ NULL }
};

me_bind_action gambatte_ctrl_actions[] =
{
	{ "UP       ",  1 << RETRO_DEVICE_ID_JOYPAD_UP},
	{ "DOWN     ",  1 << RETRO_DEVICE_ID_JOYPAD_DOWN },
	{ "LEFT     ",  1 << RETRO_DEVICE_ID_JOYPAD_LEFT },
	{ "RIGHT    ",  1 << RETRO_DEVICE_ID_JOYPAD_RIGHT },
	{ "A BUTTON ",  1 << RETRO_DEVICE_ID_JOYPAD_A },
	{ "B BUTTON ",  1 << RETRO_DEVICE_ID_JOYPAD_B },
	{ "A TURBO  ",  1 << RETRO_DEVICE_ID_JOYPAD_X },
	{ "B TURBO  ",  1 << RETRO_DEVICE_ID_JOYPAD_Y },
	{ "START    ",  1 << RETRO_DEVICE_ID_JOYPAD_START },
	{ "SELECT   ",  1 << RETRO_DEVICE_ID_JOYPAD_SELECT },
	{ NULL,       0 }
};

#define gambatte_overrides {                                    \
	.core_name = "gambatte",                                \
	.actions = gambatte_ctrl_actions,                       \
	.action_size = array_size(gambatte_ctrl_actions),       \
	.options = gambatte_core_option_overrides               \
}
