#!/bin/sh

git fetch --all
git merge upstream/main
git submodule update --init
make distclean
make picoarch platform=funkey-s
cp README.funkey-s.md opk/
cp picoarch opk/

rm -f *.opk
mksquashfs opk/ picoarch_funkey-s.opk -all-root -noappend -no-exports -no-xattrs
md5sum picoarch
rm -f opk/README.funkey-s.md
